### ISSUE TITLE
How to get data from other bluetooth devices ?

### ISSUE THREAD

**Issue by hferreira** [jamieowen/AirNativeiOS-Bluetooth#1]
This is a very cool native extension but is limited to connect between iDevices and how to get data from other devices (in this case read data is enought) ?

**Comment by jamieowen** [comment]
I'm assuming you mean Android and/or Bluetooth devices in general?

The GKSession/GKPPC classes used with this Native Extensions are from the Apple Game Kit SDK, so in true Apple fashion they will only communicate with other Apple devices.   I haven't looked into trying to communicate with other non-apple devices unfortunately.  Its not a feature of the GK classes that I know of, you'd need to use some other iOS Apis for that.

As for reading data, In a bluetooth setup like this, you wouldn't directly "read" data direct from a Peer.  The GKSession object lets you send data to ONE peer or ALL peers.  And then receive data along with the peerID that the data came from.  From this you can query peers with a message and have the peer respond with the data you require.
It's up to the programmer to create the system of messages that allows the communication to take place.

**Comment by hferreira** [comment]
Yes, it's to connect other non-Apple devices like Android for example.

Meanwhile I also realease what you said. This is for talk each other between iDevices.

I have deep search for this and have founded this possibility thru Core.Bluetooth.framework (only for iPhone4S or higher and New iPad or higher but I can live with that).

I'm a flex developer and this is my first contact with objective-c and xcode so this is a big chalange for at once learn objective-c, familiarize with xcode environment, build a native extension to be consumed by a flex sample project and at the end there is no garanties that will proper function with my target bluetooth device but I already started with the objective-c part.

**Comment by jamieowen** [comment]
Cool, let me know how it goes when you've completed it. I'd be curious to see how easy it is to communicate to other devices!

This native extension was my first test with Obj-C and I found it quite straightforward.  The only headache was having to debug and test bluetooth on two devices :)

**Comment by hferreira** [comment]
OK. I will try to go as far I can and let's see the results.

**Comment by th0f** [comment]
Any success? I would be highly interested in such addition!

**Comment by saar62097** [comment]
hey hferreira,
any success in the time passed connecting iOS device to a non iOS device through BT with AIR/Flex mobile app?

**Comment by hferreira** [comment]
Unfortunately not. I am now dedicated to other project.

2013/1/31 saar62097 notifications@github.com

**Comment by saar62097** [comment]
thnx
