### ISSUE TITLE
 ld: framework not found GameKit Compilation failed while executing : ld64

### ISSUE THREAD

**Issue by play175** [jamieowen/AirNativeiOS-Bluetooth#2]
ld: framework not found GameKit
Compilation failed while executing : ld64

how to fix that?? plz tell me,thx

**Comment by jamieowen** [comment]
Are you using ANT to compile? This sounds like you are not including the GameKit Libraries into your XCode project? Or perhaps the paths to these libraries are not valid in your iOS SDK version.

If you look at item 18 on this blog entry it might help :
http://www.richardlord.net/blog/20-tips-for-creating-air-native-extensions-for-ios

**Comment by play175** [comment]
thank you very much！！i got it
