### ISSUE TITLE
Stage loses mouse interactions

### ISSUE THREAD

**Issue by ksandapen** [jamieowen/AirNativeiOS-Bluetooth#3]
Test parameters:
- Flash Builder 4.6
- Mobile ActionScript Project
- Rendering Mode - Direct
- depthAndStencil - true
- iOS 6

Steps to reproduce:

1) Create the Picker(same as in example)
2) Picker is shown
3) User cancels or connects to device
4) Connection is established 
5) No mouse events are being captured on the stage elements.

**Comment by ksandapen** [comment]
Found the issue..http://forums.adobe.com/message/4794553

**Comment by jamieowen** [comment]
Cool. Thanks for letting me know the problem.
