### ISSUE TITLE
If the display is in sleep mode, is it possible to still keep sending Bluetooth data? Or if it's in progress will it stop?

### ISSUE THREAD

**Issue by brybam** [jamieowen/AirNativeiOS-Bluetooth#4]

**Comment by jamieowen** [comment]
I'm not completely sure. You will have to try that out.

But bare in mind, this is a native extension written using the IOS GameKit Peer2Peer libraries. These libraries are really for use in real-time games so if you are planning on sending large files ( and then putting the device to sleep ), you may want to look into more generic iOS bluetooth libraries such as Core.Bluetooth.
