### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by ThijsRoumen** [jamieowen/AirNativeiOS-Bluetooth#9]
This extension seems to be exactly what I needed: I want to connect a bluetooth device with my iOS device. Is it possible to use this extension for that? So far I did not really manage to get it running. Do you have a sample flash file where this extension is implemented so I can see what is going wrong?

**Comment by jamieowen** [comment]
Hey mate.

This might not be what you are looking for as it uses the iOS GameKit P2P libraries.  So can only communicate with other iOS devices not generic Bluetooth devices.  You need to use iOS CoreBluetooth for that.

If this is what you are after, I'm not really supporting this project anymore. Too much other stuff to do! And their is also some complete GameKit AIR Native extensions out there for pretty cheap!

Cheers,

Jamie

**Comment by ThijsRoumen** [comment]
thanks again for the response, by now I have written my own ANE which works very well! You were right indeed!
